[{
	"resource": "/c:/Users/gazou/Documents/GitHub/marketformation-api-clone/marketformation-api/app/api/stripe/checkout/route.ts",
	"owner": "typescript",
	"code": "2554",
	"severity": 8,
	"message": "Expected 1 arguments, but got 2.",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 29,
	"endLineNumber": 9,
	"endColumn": 85,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/gazou/Documents/GitHub/marketformation-api-clone/marketformation-api/app/api/stripe/checkout/route.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 61,
	"endLineNumber": 9,
	"endColumn": 70,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/gazou/Documents/GitHub/marketformation-api-clone/marketformation-api/app/api/stripe/portal/route.ts",
	"owner": "typescript",
	"code": "2554",
	"severity": 8,
	"message": "Expected 1 arguments, but got 2.",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 29,
	"endLineNumber": 9,
	"endColumn": 85,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/gazou/Documents/GitHub/marketformation-api-clone/marketformation-api/app/api/stripe/portal/route.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 61,
	"endLineNumber": 9,
	"endColumn": 70,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/gazou/Documents/GitHub/marketformation-api-clone/marketformation-api/app/api/subscription/route.ts",
	"owner": "typescript",
	"code": "2351",
	"severity": 8,
	"message": "This expression is not constructable.\n  Type 'typeof import(\"stripe\")' has no construct signatures.",
	"source": "ts",
	"startLineNumber": 17,
	"startColumn": 14,
	"endLineNumber": 17,
	"endColumn": 23,
	"origin": "extHost1"
}]